allowBuilds:
  '@nestjs/core': true
  electron: true
  electron-winstaller: true
  esbuild: true
  simple-git-hooks: true

overrides:
  '@eslint-react/eslint-plugin': ^5.8.7

shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver
