allowBuilds:
  '@nestjs/core': true
  electron: true
  electron-winstaller: true
  esbuild: true
  simple-git-hooks: true

overrides:
  '@eslint-react/eslint-plugin': ^5.0.0

shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@5.7.2
  - semver@6.3.1
